---

- name: install virtualbox dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - dkms
      - wget

- name: add virtualbox repository
  copy:
    src: files/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644
  register: virtualbox_repository

- name: add virtualbox repository gpg key
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- name: get kernel version
  shell: |
    set -o pipefail
    uname -r | egrep -o '^[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  register: virtualbox_kernel_version
  changed_when: false

- name: install kernel-devel and kernel-headers
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "kernel-devel-{{ virtualbox_kernel_version.stdout }}"
      - "kernel-headers-{{ virtualbox_kernel_version.stdout }}"

- name: install VirtualBox
  package:
    name: VirtualBox-{{ virtualbox_version }}
    state: present
  register: virtualbox_installed

- name: run vboxdrv setup
  shell: /usr/lib/virtualbox/vboxdrv.sh setup
  when: virtualbox_installed.changed
  register: virtualbox_vboxdrv
  ignore_errors: True

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: virtualbox_extpack_list

- name: Download VirtualBox extension pack
  get_url:
    validate_certs: yes
    url: "{{ virtualbox_extension_pack_url }}"
    dest: "/tmp"
    mode: 0700
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'
  register: virtualbox_extension_pack

- name: Install VirtualBox extension pack
  shell: |
    set -o pipefail
    echo y | VBoxManage extpack install --replace {{ virtualbox_extension_pack.dest }}
    rm -f "{{ virtualbox_extension_pack.dest }}"
  args:
    executable: /bin/bash
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'

- name: install vagrant
  dnf:
    name: "https://releases.hashicorp.com/vagrant/{{ virtualbox_vagrant_version }}/vagrant_{{ virtualbox_vagrant_version }}_x86_64.rpm"
    state: present

- name: failed to install VritualBox
  fail: msg="failed to install VritualBox"
  when: ((virtualbox_vboxdrv is failed) and (not virtualbox_role_debug|bool))
