---

- name: install virtualbox dependencies
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms

- name: add virtualbox repository
  copy:
    src: files/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: 0644
  register: virtualbox_repository

- name: add virtualbox repository gpg key
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- name: yum makecache
  shell: yum -q -y makecache fast warn=no
  when: virtualbox_repository is changed

- name: install VirtualBox
  yum:
    name: VirtualBox-{{virtualbox_version}}
    state: present
    update_cache: yes
  register: virtualbox_installed

- name: get kernel version
  shell: uname -r
  register: virtualbox_kernel_version
  changed_when: false
  when: virtualbox_installed.changed

- name: install kernel-devel
  yum:
    name: "kernel-devel-{{ virtualbox_kernel_version.stdout }}"
    state: present
    update_cache: yes
  when: virtualbox_installed.changed
  ignore_errors: True
  register: virtualbox_kernel

- name: install kernel-devel
  yum:
    name: "kernel-devel"
    state: present
  when: virtualbox_kernel is failed

- name: run vboxdrv setup
  shell: >
    export KERN_DIR="/usr/src/kernels/$(rpm -q kernel-devel | head -n 1 | cut -c 14-)" && \
    /usr/lib/virtualbox/vboxdrv.sh setup
    args:
      executable: /bin/bash
  when: virtualbox_installed.changed
  register: virtualbox_vboxdrv
  ignore_errors: True

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: virtualbox_extpack_list

- name: Download VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{virtualbox_version}}.2/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_version}}.28.vbox-extpack"
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_version}}.28.vbox-extpack"
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'

- name: failed to install VritualBox
  fail: msg="failed to install VritualBox"
  when: ((virtualbox_vboxdrv is failed) and (virtualbox_role_debug|bool == false))
