---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/8
provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
# verifier:
#   name: testinfra
#   lint:
#     name: flake8
